// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'test.idk.models.Application' );
goog.provide( 'test.idk.models.ApplicationDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
test.idk.models.ApplicationDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.name = undefined;

    /**
     * @type {string}
     */
    this.version = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( test.idk.models.ApplicationDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
test.idk.models.Application = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( test.idk.models.Application, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {test.idk.models.ApplicationDatarow}
*/
test.idk.models.Application.prototype.DatarowConstructor = test.idk.models.ApplicationDatarow;

/**
* Return test.idk.models.ApplicationDatarow schema object.
* @override
* @returns {Object}
*/
test.idk.models.Application.prototype.getDatarowSchema = function( ){

return {
        name: {
                index: 0,
                type: zz.models.enums.FieldType.STRING,
                required: false
        },
        version: {
                index: 1,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};