// This file was autogenerated by idk compile models.
// Please do not edit.

goog.provide( 'test.idk.models.Table' );
goog.provide( 'test.idk.models.TableDatarow' );

goog.require( 'zz.models.Datarow' );
goog.require( 'zz.models.Dataset' );
goog.require( 'zz.models.enums.FieldType' );



/**
* @param {!zz.models.Dataset} dataset
* @param {?Array.<string>} opt_data
* @extends {zz.models.Datarow}
* @constructor
*/
test.idk.models.TableDatarow = function( dataset, opt_data ){

    /**
     * @type {string}
     */
    this.title = undefined;



/**
* Call parent constructor.
*/
zz.models.Datarow.call( this, dataset, opt_data );
};

goog.inherits( test.idk.models.TableDatarow, zz.models.Datarow );

/**
* @param {goog.event.EventTarget=} opt_parent
* @param {Array.<Array>=} opt_data
* @extends {zz.models.Dataset}
* @constructor
*/
test.idk.models.Table = function( opt_parent, opt_data ){

zz.models.Dataset.call( this, opt_parent, opt_data );
};
goog.inherits( test.idk.models.Table, zz.models.Dataset );

/**
* Current dataset row type.
* @constructor
* @overwrite
* @type {test.idk.models.TableDatarow}
*/
test.idk.models.Table.prototype.DatarowConstructor = test.idk.models.TableDatarow;

/**
* Return test.idk.models.TableDatarow schema object.
* @override
* @returns {Object}
*/
test.idk.models.Table.prototype.getDatarowSchema = function( ){

return {
        title: {
                index: 3,
                type: zz.models.enums.FieldType.STRING,
                required: false
        }
};
};